version: '3'

services:
  depthai:
    build: ../integration_example/
    volumes:
      - ../:/work
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - ${HOME}:${HOME}:rw
    command: bash
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      TERM: xterm-256color
    group_add:
      - sudo
    user: ${DOCKER_USER}