name: Zoo Helper

on:
  workflow_dispatch:

env:
  CMAKE_WINDOWS_SDK_VERSION: '10.0.18362.0'
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  build-zoo-helper:
    runs-on: ubuntu-latest
    steps:
      - name: Cache .hunter folder
        uses: actions/cache@v3
        with:
          path: ~/.hunter
          key: hunter-ubuntu-latest-v3-develop

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
           core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
           core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libusb-1.0-0-dev pkg-config

      - name: Installing libusb1-devel dependency
        run: yum install -y libusb1-devel perl-core curl zip unzip tar ninja-build  zlib-devel curl-devel xcb-util-renderutil-devel xcb-util-devel xcb-util-image-devel xcb-util-keysyms-devel xcb-util-wm-devel mesa-libGL-devel libxkbcommon-devel libxkbcommon-x11-devel libXi-devel libXrandr-devel libXtst-devel libudev-devel lapack-devel nasm libtool autoconf automake
      
      - name: Installing cmake dependency
        run: |
          /opt/python/cp38-cp38/bin/python3.8 -m pip install cmake
          ln -s /opt/python/cp38-cp38/bin/cmake /bin/

      - name: Configure project
        run: cmake -S . -B build -DDEPTHAI_ENABLE_CURL=ON

      - name: Build zoo_helper
        run: cmake --build build --target zoo_helper --parallel 4