name: Zoo Helper

on:
  workflow_dispatch:

env:
  CMAKE_WINDOWS_SDK_VERSION: '10.0.18362.0'
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  build-zoo-helper:
    runs-on: almalinux-8
    steps:
      - name: Cache .hunter folder
        uses: actions/cache@v3
        with:
          path: ~/.hunter
          key: hunter-almalinux-8-v3-develop

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
           core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
           core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          dnf update -y
          dnf install -y libusb-devel pkgconf-pkg-config bison autoconf libtool libXi-devel libXtst-devel cmake git zip perl-core python39
          dnf install -y libXrandr-devel libX11-devel libXft-devel libXext-devel nasm flex systemd-devel
          dnf install -y gcc-c++ automake libtool-ltdl-devel wget
          wget https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/nasm-2.16.01.tar.gz && tar -xzf nasm-2.16.01.tar.gz && cd nasm-2.16.01 && ./configure && make && make install # install nasm - build from source
          pip3 install jinja2
          
      - name: Configure project
        run: cmake -S . -B build -DDEPTHAI_ENABLE_CURL=ON

      - name: Build zoo_helper
        run: cmake --build build --target zoo_helper --parallel 4

      - name: Upload zoo_helper to artifactory
        run: |
          bash ./ci/upload-artifactory-zoo-helper.sh
        env:
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_PASS: ${{ secrets.ARTIFACTORY_PASS }}
